##  Business Problem: Real-Time Pedestrian and Vehicle Detection for Traffic Monitoring and Surveillance

With the growing need for enhanced public safety and efficient traffic management, automating pedestrian and vehicle detection can provide significant value. This project addresses the challenge of identifying pedestrians and vehicles in real-time video feeds, offering a scalable solution for applications such as:

- **Traffic monitoring** for smart city infrastructure
- **Surveillance** for security and safety
- **Autonomous vehicles** for real-time decision-making

By leveraging OpenCV and Haar cascades, this system enables effective detection and monitoring, enhancing situational awareness and enabling proactive responses in various real-world scenarios.


In [1]:
import cv2
import numpy as np
import warnings
warnings.simplefilter('ignore')

## Load the image

In [2]:
img=cv2.imread("image_examples-20250315T132046Z-001/image_examples/Modi.jpg",1)
print(img)

[[[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 ...

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]

 [[255 255 255]
  [255 255 255]
  [255 255 255]
  ...
  [255 255 255]
  [255 255 255]
  [255 255 255]]]


In [3]:
img.shape

(1358, 1500, 3)

In [4]:
type(img)

numpy.ndarray

## Display the Image

In [5]:
cv2.imshow('PM',img)
cv2.waitKey(5000)       # Displays image for 5 seconds
cv2.destroyAllWindows()

## Resize the Image

In [6]:
resized_img=cv2.resize(img,(500,500))
gray_img=cv2.cvtColor(resized_img,cv2.COLOR_BGR2GRAY)

cv2.imshow('B/W PM',gray_img)
cv2.waitKey(4000)
cv2.destroyAllWindows()

## Save the Image

In [7]:
cv2.imwrite('bw_modi.jpg',gray_img)

True

### Implementing Haar Cascade Classifier for Face Detection

In [8]:
face_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_frontalface_default.xml')

img=cv2.imread("image_examples-20250315T132046Z-001/image_examples/Modi.jpg",1)
# img=cv2.imread("C:/Users/user/Pictures/Saved Pictures/IMG_7594.jpg",1)
img=cv2.resize(img,(500,500))
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=face_model.detectMultiScale(img,1.3,5)

if len(faces) == 0:
    print("No faces detected.")
else:
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(0,21,220),2)  # (x, y) → Top-left corner of the rectangle.
                                                         # (x + w, y + h) → Bottom-right corner (calculated using width w and height h).

cv2.imshow('Face_Detection',img)
cv2.waitKey(0)                        #  waits indefinitely for a key press, ensuring the image window remains open.
cv2.destroyAllWindows()

### Implementing Haar Cascade Classifier for Face & Eye Detection

In [9]:
face_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_frontalface_default.xml')
eye_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_eye.xml')

# Check if the classifiers are loaded properly
if face_model.empty():
    print("Error: Face cascade file not loaded.")
if eye_model.empty():
    print("Error: Eye cascade file not loaded.")

# img=cv2.imread("C:/Users/user/Pictures/Saved Pictures/IMG_7594.jpg",1)
img=cv2.imread("image_examples-20250315T132046Z-001/image_examples/Modi.jpg",1)
img=cv2.resize(img,(500,500))
img=cv2.cvtColor(img,cv2.COLOR_BGR2GRAY)

faces=face_model.detectMultiScale(img,1.3,6)

if len(faces) == 0:
    print("No faces detected.")
else:
    for (x,y,w,h) in faces:
        cv2.rectangle(img,(x,y),(x+w,y+h),(255,0,120),2)
        roi_img=img[y:y+h,x:x+w]               # img[y:y+h, x:x+w] because y corresponds to rows (height) and x corresponds to columns (width)
        eyes=eye_model.detectMultiScale(roi_img)
        for ex,ey,ew,eh in eyes:
            if len(eyes) == 0:
                print("No faces detected.")
            else:
                cv2.rectangle(roi_img,(ex,ey),(ex+ew,ey+eh),(0,0,255),2)

cv2.imshow('Face_Eye_Detection',img)
cv2.waitKey(0)                        #  waits indefinitely for a key press, ensuring the image window remains open.
cv2.destroyAllWindows()

### Face Recognition with WebCam

In [10]:
import cv2

video=cv2.VideoCapture(0)

while True:
    check,frame=video.read()

    if not check:
        print("Failed to grab frame")
        break
    
    gray_frame=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    cv2.imshow("video",gray_frame)
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()

Failed to grab frame


### Face Recognition with WebCam Using HaarCascade Classifier

In [11]:
face_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_frontalface_default.xml')
eye_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_eye.xml')

# Check if the classifiers are loaded properly
if face_model.empty():
    print("Error: Face cascade file not loaded.")
if eye_model.empty():
    print("Error: Eye cascade file not loaded.")
    
def detect(gray,frame):
    faces=face_model.detectMultiScale(gray,1.3,5)
    for x,y,w,h in faces:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,0),2)
        roi_gray=gray[y:y+h,x:x+w]
        roi_color=frame[y:y+h,x:x+w]
        eyes=eye_model.detectMultiScale(roi_gray,1.1,3)
        for (ex,ey,ew,eh) in eyes:
            cv2.rectangle(roi_color,(ex,ey),(ex+ew,ey+eh),(0,255,0),2)
    return frame

video=cv2.VideoCapture(0)

while True:
    check,frame=video.read()
    if not check:
        print("Failed to grab frame")
        break
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    face_detect=detect(gray,frame)
    cv2.imshow("Face Recognition",face_detect)
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()

Failed to grab frame


### Pedesterian Detection

In [24]:
import cv2

body_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_fullbody.xml')

if body_model.empty():
    print("Error: Full Body cascade file not loaded.")
    exit()

video=cv2.VideoCapture('image_examples-20250315T132046Z-001/image_examples/walking.avi')


while video.isOpened():
    check,frame=video.read()
    
    if not check:
        print("Failed to grab frame")
        break
        
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bodies=body_model.detectMultiScale(gray,1.1,3)
    
    for x,y,w,h in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)
        
    cv2.imshow("Pedesterian Detection",frame)
    
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()

### Car Detection

In [19]:
import cv2
import time

car_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_car.xml')
body_model=cv2.CascadeClassifier('Haarcascades-20250315T132046Z-001/Haarcascades/haarcascade_fullbody.xml')

if body_model.empty():
    print("Error: Full Body cascade file not loaded.")
    exit()

video=cv2.VideoCapture('image_examples-20250315T132046Z-001/image_examples/cars.avi')

while video.isOpened():
    time.sleep(0.05)
    check,frame=video.read()
    
    if not check:
        print("Failed to grab frame")
        break
        
    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bodies=car_model.detectMultiScale(gray,1.1,3)
    
    for x,y,w,h in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(0,255,255),2)

    gray=cv2.cvtColor(frame,cv2.COLOR_BGR2GRAY)
    bodies=body_model.detectMultiScale(gray,1.1,3)
    
    for x,y,w,h in bodies:
        cv2.rectangle(frame,(x,y),(x+w,y+h),(255,0,255),2)
        
    cv2.imshow("Car Detection",frame)
    
    if cv2.waitKey(1)==ord('q'):
        break

video.release()
cv2.destroyAllWindows()

## ✅ Conclusion

The real-time pedestrian and vehicle detection system developed using OpenCV demonstrates the potential of computer vision in enhancing public safety and traffic monitoring. With the use of Haar cascades and optimized for live video feeds, the system successfully detects and classifies pedestrians and vehicles with high efficiency. 

- Achieved real-time processing capabilities, enabling immediate detection and action.
- Delivered a scalable solution for various real-world applications, such as traffic monitoring and surveillance.

This project highlights the power of computer vision and AI in transforming everyday environments for greater security and operational efficiency.
